using System.Collections.Generic;
using QuestionSystem;

public class CarbohydratesQuestionDatabase : IQuestionDatabase
{
    private bool databaseInDevelopment = false;
    
    private List<Question> questions = new List<Question>
    {
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "Qual a fórmula geral dos monossacarídeos?",
            answers = new string[] {
                "(CH<sub>2</sub> O)<sub>n</sub>",
                "C<sub>n</sub> H<sub>2n</sub> O<sub>n</sub>",
                "C<sub>n</sub> H<sub>2n-2</sub> O<sub>n</sub>",
                "C<sub>n</sub> H<sub>2n+2</sub> O<sub>n</sub>"
            },
            correctIndex = 0,
            questionNumber = 1,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "carbohydrates_001",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "lembrar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Os monossacarídeos, por serem hidratos de carbono simples, seguem a fórmula empírica (CH2O)n. A alternativa correta mostra exatamente essa proporção de um carbono para cada molécula de água." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "O que diferencia uma aldose de uma cetose?",
            answers = new string[] {"Grupo funcional aldeído vs. cetona", "Número de átomos de carbono", "Presença de oxigênio", "Solubilidade em água"},
            correctIndex = 0,
            questionNumber = 2,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "carbohydrates_002",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "compreender",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A diferença central está no grupo carbonila. Se o grupo estiver na extremidade da cadeia, forma um aldeído (aldose). Se estiver no meio da cadeia, forma uma cetona (cetose)." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "Qual das estruturas representa uma cetose?",
            answers = new string[] {
                "AnswerImages/CarbohydrateDB/D-aldotriose",
                "AnswerImages/CarbohydrateDB/D-aldotetrose",
                "AnswerImages/CarbohydrateDB/D-cetotetrose",
                "AnswerImages/CarbohydrateDB/D-aldopentose"
            },
            correctIndex = 2,
            questionNumber = 3,
            isImageAnswer = true,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "carbohydrates_003",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "aplicar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Uma cetose possui o grupo funcional cetona (C=O) sempre em um carbono secundário. Observe a estrutura onde a dupla ligação com oxigênio não está na extremidade." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "Qual estrutura representa uma aldotetrose",
            answers = new string[] {
                "AnswerImages/CarbohydrateDB/D-aldotriose",
                "AnswerImages/CarbohydrateDB/D-aldotetrose",
                "AnswerImages/CarbohydrateDB/D-cetotetrose",
                "AnswerImages/CarbohydrateDB/D-aldopentose"
            },
            correctIndex = 1,
            questionNumber = 4,
            isImageAnswer = true,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "carbohydrates_004",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "aplicar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "O termo 'aldo' indica a presença de um grupo aldeído (C=O na extremidade), enquanto 'tetrose' indica 4 átomos de carbono no total da cadeia." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "AnswerImages/CarbohydrateDB/L-glicose",
                "AnswerImages/CarbohydrateDB/D-glicose",
                "AnswerImages/CarbohydrateDB/D-galactose",
                "AnswerImages/CarbohydrateDB/D-frutose"
            },
            correctIndex = 0,
            questionNumber = 5,
            isImageAnswer = true,
            isImageQuestion = true,
            questionImagePath = "QuestionImages/CarbohydrateDB/carbohydrateDB_ImageQuestionContainer5",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "carbohydrates_005",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "analisar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A isomeria D ou L é definida pelo carbono quiral mais distante do grupo carbonila. Se o grupo OH deste carbono estiver à direita, é da série D; à esquerda, série L." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "O que são epímeros?",
            answers = new string[] {
                "Diastereoisômeros que diferem em um único centro quiral",
                "Enanciômeros que diferem em todos os centros quirais",
                "Isômeros que diferem no número de átomos de carbono",
                "Isômeros que diferem no tipo de ligação"},
            correctIndex = 0,
            questionNumber = 6,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "carbohydrates_006",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "compreender",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Epímeros são um tipo específico de diastereoisômeros. Eles se diferenciam pela configuração espacial ao redor de apenas um carbono quiral da cadeia." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "AnswerImages/CarbohydrateDB/L-glicose",
                "AnswerImages/CarbohydrateDB/D-glicose",
                "AnswerImages/CarbohydrateDB/L-frutose",
                "AnswerImages/CarbohydrateDB/D-tagatose"
            },
            correctIndex = 3,
            questionNumber = 7,
            isImageAnswer = true,
            isImageQuestion = true,
            questionImagePath = "QuestionImages/CarbohydrateDB/carbohydrateDB_ImageQuestionContainer7",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "carbohydrates_007",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "analisar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A D-tagatose é uma cetose que atua como adoçante. Note que ela possui a hidroxila do carbono quiral mais distante à direita (série D) e o grupo cetona no carbono 2." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "O que são anômeros?",
            answers = new string[] {
                "Isômeros cíclicos que diferem na configuração do carbono anomérico",
                "Isômeros de cadeia aberta",
                "Isômeros que diferem na posição do grupo hidroxila",
                "Isômeros que diferem no tipo de ligação"
            },
            correctIndex = 0,
            questionNumber = 8,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "carbohydrates_008",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "compreender",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Anômeros surgem apenas quando o açúcar forma uma estrutura cíclica. O carbono do grupo carbonila se torna um novo centro quiral (carbono anomérico), gerando formas alfa e beta." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "AnswerImages/CarbohydrateDB/L-glicose",
                "AnswerImages/CarbohydrateDB/alfa-galactopiranose",
                "AnswerImages/CarbohydrateDB/beta-galactosamina",
                "AnswerImages/CarbohydrateDB/alfa-glicopiranose"
            },
            correctIndex = 3,
            questionNumber = 9,
            isImageAnswer = true,
            isImageQuestion = true,
            questionImagePath = "QuestionImages/CarbohydrateDB/carbohydrateDB_ImageQuestionContainer9",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "carbohydrates_009",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "analisar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "O nome 'glico' vem da glicose, e 'piranose' indica um anel de 6 átomos (5 carbonos e 1 oxigênio). O anômero alfa possui o grupo OH do carbono anomérico direcionado para baixo ou em oposição ao grupo CH2OH." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "Qual o principal dissacarídeo encontrado na cana-de-açúcar?",
            answers = new string[] {"Maltose", "Lactose", "Sacarose", "Celobiose"},
            correctIndex = 2,
            questionNumber = 10,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "carbohydrates_010",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "lembrar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A cana-de-açúcar é a principal fonte comercial de sacarose, um dissacarídeo de transporte muito comum nas plantas, não-redutor, que adoça os alimentos." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "Qual dissacarídeo é o açúcar do leite?",
            answers = new string[] {"Maltose", "Lactose", "Sacarose", "Celobiose"},
            correctIndex = 1,
            questionNumber = 11,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "carbohydrates_011",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "lembrar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A lactose é o açúcar característico do leite dos mamíferos. Ela é formada pela união de uma molécula de glicose com uma de galactose." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "Qual o tipo de ligação que une os monossacarídeos em um dissacarídeo?",
            answers = new string[] {"Ligação peptídica", "Ligação glicosídica", "Ligação éster", "Ligação fosfodiéster"},
            correctIndex = 1,
            questionNumber = 12,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "carbohydrates_012",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "compreender",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Os açúcares se unem através de uma condensação que resulta na ligação glicosídica. Isso ocorre entre o grupo OH de um açúcar e o OH de outro, liberando uma molécula de água." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "monossacarídeo",
                "dissacarídeo",
                "oligossacarídeo",
                "polissacarídeo"
            },
            correctIndex = 1,
            questionNumber = 13,
            isImageAnswer = false,
            isImageQuestion = true,
            questionImagePath = "QuestionImages/CarbohydrateDB/carbohydrateDB_ImageQuestionContainer13",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "carbohydrates_013",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "aplicar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Um dissacarídeo é formado pela união de dois monossacarídeos. Mono significa um, di significa dois, oligo significa poucos e poli significa muitos." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "1-beta-4",
                "1-alfa-4",
                "1-beta-2",
                "1-alfa-2"
            },
            correctIndex = 0,
            questionNumber = 14,
            isImageAnswer = false,
            isImageQuestion = true,
            questionImagePath = "QuestionImages/CarbohydrateDB/carbohydrateDB_ImageQuestionContainer14",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "carbohydrates_014",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "analisar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Na lactose, a ligação ocorre entre o carbono 1 da galactose na forma beta e o carbono 4 da glicose. O OH da galactose (forma beta) aponta para o mesmo lado do grupo terminal." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "Qual o principal polissacarídeo de reserva energética em plantas?",
            answers = new string[] {"Celulose", "Quitina", "Amido", "Glicogênio"},
            correctIndex = 2,
            questionNumber = 15,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "carbohydrates_015",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "lembrar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "As plantas acumulam energia através do amido, que fica guardado em grânulos nas células vegetais. Ele é um polímero de glicose altamente energético." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "Qual o principal polissacarídeo de reserva energética em animais?",
            answers = new string[] {"Celulose", "Quitina", "Amido", "Glicogênio"},
            correctIndex = 3,
            questionNumber = 16,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "carbohydrates_016",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "lembrar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Nos animais, a glicose excedente é polimerizada em glicogênio. Ele fica armazenado principalmente no fígado e nos tecidos musculares para uso rápido." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "Qual a principal diferença estrutural entre amilose e amilopectina?",
            answers = new string[] {"Ramificação", "Tipo de ligação glicosídica", "Tipo de monossacarídeo", "Peso molecular"},
            correctIndex = 0,
            questionNumber = 17,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "carbohydrates_017",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "compreender",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "O amido é composto por amilose e amilopectina. Enquanto a amilose forma uma cadeia linear em espiral, a amilopectina apresenta ramificações frequentes através de ligações alfa(1->6)." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "Qual o tipo de ligação glicosídica predominante na celulose?",
            answers = new string[] {"alfa(1 -> 4)", "alfa(1 -> 6)", "beta(1 -> 4)", "beta(1 -> 6)"},
            correctIndex = 2,
            questionNumber = 18,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "carbohydrates_018",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "lembrar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Na celulose, as moléculas de glicose se unem por ligações beta(1->4). Isso permite que formem fibras estendidas e muito resistentes, essenciais para a parede celular vegetal." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "Qual o tipo de ligação glicosídica predominante no amido?",
            answers = new string[] {"alfa(1 -> 4)", "alfa(1 -> 6)", "beta(1 -> 4)", "beta(1 -> 6)"},
            correctIndex = 0,
            questionNumber = 19,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "carbohydrates_019",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "lembrar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "O amido (tanto na amilose quanto na amilopectina) tem sua cadeia principal estruturada com ligações do tipo alfa(1->4), que promovem um enrolamento da molécula." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "Qual enzima hidrolisa o amido?",
            answers = new string[] {"Celulase", "Quitina", "Amilase", "Lactase"},
            correctIndex = 2,
            questionNumber = 20,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "carbohydrates_020",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "lembrar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A quebra (hidrólise) do amido começa na boca e continua no intestino através da enzima amilase, que quebra as ligações alfa(1->4) liberando açúcares menores." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "Qual enzima hidrolisa a celulose?",
            answers = new string[] {"Celulase", "Quitina", "Amilase", "Lactase"},
            correctIndex = 0,
            questionNumber = 21,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "carbohydrates_021",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "lembrar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Para digerir a celulose e quebrar as fortes ligações beta(1->4), é necessária a enzima celulase. Os humanos não produzem essa enzima, por isso a celulose atua como fibra alimentar." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "O que são glicoproteínas?",
            answers = new string[] {
                "Proteínas ligadas a carboidratos",
                "Proteínas ligadas a lipídeos",
                "Proteínas ligadas a ácidos nucleicos",
                "Proteínas ligadas a outras proteínas"
            },
            correctIndex = 0,
            questionNumber = 22,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "carbohydrates_022",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "lembrar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "As glicoproteínas são proteínas que contêm uma ou mais cadeias de carboidratos ligadas covalentemente à sua estrutura. Elas atuam em membranas, como marcadores e receptores." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "O que são glicosaminoglicanos?",
            answers = new string[] {
                "Homopolissacarídeos que presentes no citoplasma celular.",
                "Heteropolissacarídeos que compõe a matriz extracelular.",
                "São glicoses ligadas a aminas presentes no sangue",
                "São dissacarídeos ligados à proteínas"
            },
            correctIndex = 1,
            questionNumber = 23,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "carbohydrates_023",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "compreender",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Glicosaminoglicanos são cadeias longas de heteropolissacarídeos. Eles compõem a matriz extracelular dos animais, formando um gel que preenche o espaço entre as células." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "O que são proteoglicanos?",
            answers = new string[] {
                "Glicosaminoglicanos ligados a proteínas",
                "Glicoproteínas ligadas a lipídeos",
                "Glicolipídeos ligados a proteínas",
                "Proteínas ligadas a ácidos nucleicos"
            },
            correctIndex = 0,
            questionNumber = 24,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "carbohydrates_024",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "compreender",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Quando glicosaminoglicanos (carboidratos complexos) se ligam covalentemente a uma proteína central, formam os proteoglicanos. Estes são abundantes na matriz extracelular." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "Onde são encontradas os glicosaminoglicanos?",
            answers = new string[] {"Matriz extracelular", "Membrana celular", "Citoplasma", "Todas as alternativas acima"},
            correctIndex = 0,
            questionNumber = 25,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "carbohydrates_025",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "lembrar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A grande função dos glicosaminoglicanos é preencher espaços fora das células. Eles retêm muita água e compõem a matriz extracelular de tecidos conjuntivos." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "Identifique abaixo um componente estrutural dos glicosaminoglicanos.",
            answers = new string[] {
                "AnswerImages/CarbohydrateDB/alfa-glicopiranose",
                "AnswerImages/CarbohydrateDB/beta-glicopiranose",
                "AnswerImages/CarbohydrateDB/beta-galactosamina",
                "AnswerImages/CarbohydrateDB/D-aldopentose"
            },
            correctIndex = 2,
            questionNumber = 26,
            isImageAnswer = true,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "carbohydrates_026",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "aplicar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A beta-galactosamina é um derivado de açúcar que possui um grupo amina substituindo uma hidroxila. Esses derivados aminados são a base dos glicosaminoglicanos." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "Indique abaixo a estrutura do ácido hialurônico, que é um glicosaminoglicano cujo monômero é formado pelo ácido glicurônico e pelo ácido N-acetil-glicosamina.",
            answers = new string[] {
                "AnswerImages/CarbohydrateDB/dermatan",
                "AnswerImages/CarbohydrateDB/condroitin",
                "AnswerImages/CarbohydrateDB/queratan",
                "AnswerImages/CarbohydrateDB/hialuronico"
            },
            correctIndex = 3,
            questionNumber = 27,
            isImageAnswer = true,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "carbohydrates_027",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "analisar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "O ácido hialurônico possui uma estrutura repetitiva simples e sem sulfatos, diferente dos outros GAGs. Suas moléculas se ligam a muita água, formando géis transparentes e lubrificantes." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "Qual a função do ácido hialurônico?",
            answers = new string[] {"Lubrificação", "Suporte estrutural", "Viscosidade", "Todas as alternativas acima"},
            correctIndex = 3,
            questionNumber = 28,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "carbohydrates_028",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "compreender",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "O ácido hialurônico atua em múltiplas frentes devido à sua capacidade de retenção de água: lubrifica articulações, mantém a hidratação e dá suporte mecânico e viscosidade ao tecido." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "A heparina é um glicosaminoglicano com uma das maiores densidades de carga negativa dentre todas as biomoléculas dos organismos vivos. Indique abaixo o monômero que forma a heparina.",
            answers = new string[] {
                "AnswerImages/CarbohydrateDB/dermatan",
                "AnswerImages/CarbohydrateDB/condroitin",
                "AnswerImages/CarbohydrateDB/heparina",
                "AnswerImages/CarbohydrateDB/hialuronico"
            },
            correctIndex = 2,
            questionNumber = 29,
            isImageAnswer = true,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "carbohydrates_029",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "analisar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A heparina é caracterizada por seus grupos sulfato que conferem uma altíssima densidade de carga elétrica negativa. Identifique a estrutura com múltiplos grupos O-SO3-." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "Qual é uma das principais função da heparina?",
            answers = new string[] {"Anticoagulante", "Lubrificante", "Suporte estrutural", "Hormônio"},
            correctIndex = 0,
            questionNumber = 30,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "carbohydrates_030",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "analisar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Na medicina, a heparina é amplamente conhecida e utilizada como um forte agente anticoagulante. Ela inibe enzimas essenciais da cascata de coagulação sanguínea." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "1-beta-4",
                "1-alfa-4",
                "1-beta-3",
                "1-alfa-3"
            },
            correctIndex = 2,
            questionNumber = 31,
            isImageAnswer = false,
            isImageQuestion = true,
            questionImagePath = "QuestionImages/CarbohydrateDB/carbohydrateDB_ImageQuestionContainer31",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "carbohydrates_031",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "analisar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A união dos monômeros do ácido hialurônico é feita por ligações alternadas, sendo a principal a ligação beta(1->3) entre o ácido glicurônico e a N-acetilglicosamina." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "Qual a principal função do condroitin?",
            answers = new string[] {"Suporte estrutural em cartilagens", "hormônio", "Neurotransmissor", "Todas as alternativas acima"},
            correctIndex = 0,
            questionNumber = 32,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "carbohydrates_032",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "compreender",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "O condroitin sulfato é responsável pela resistência elástica das cartilagens. Ele atua amortecendo compressões mecânicas em articulações e ossos." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "1-beta-4",
                "1-alfa-4",
                "1-beta-3",
                "1-alfa-3"
            },
            correctIndex = 0,
            questionNumber = 33,
            isImageAnswer = false,
            isImageQuestion = true,
            questionImagePath = "QuestionImages/CarbohydrateDB/carbohydrateDB_ImageQuestionContainer33",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "carbohydrates_033",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "analisar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "No condroitin, as unidades dissacarídicas se polimerizam preferencialmente através de ligações glicosídicas do tipo beta(1->4) entre as unidades estruturais." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "AnswerImages/CarbohydrateDB/L-glicose",
                "AnswerImages/CarbohydrateDB/D-frutose",
                "AnswerImages/CarbohydrateDB/alfa-galactopiranose",
                "AnswerImages/CarbohydrateDB/D-galactose"
            },
            correctIndex = 1,
            questionNumber = 34,
            isImageAnswer = true,
            isImageQuestion = true,
            questionImagePath = "QuestionImages/CarbohydrateDB/carbohydrateDB_ImageQuestionContainer34",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "carbohydrates_034",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "analisar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A D-frutose é o principal açúcar das frutas. Diferente da glicose, ela é uma ceto-hexose. Procure a estrutura com um anel de 5 átomos (furanose) ou cadeia aberta com cetona." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "AnswerImages/CarbohydrateDB/L-glicose",
                "AnswerImages/CarbohydrateDB/D-frutose",
                "AnswerImages/CarbohydrateDB/D-tagatose",
                "AnswerImages/CarbohydrateDB/D-glicose"
            },
            correctIndex = 3,
            questionNumber = 35,
            isImageAnswer = true,
            isImageQuestion = true,
            questionImagePath = "QuestionImages/CarbohydrateDB/carbohydrateDB_ImageQuestionContainer35",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "carbohydrates_035",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "analisar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A D-glicose, ou dextrose, é o açúcar do sangue. Ela é uma aldo-hexose e sua conformação mais estável (cadeia aberta) tem a sequência de hidroxilas (D, E, D, D)." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "AnswerImages/CarbohydrateDB/beta-galactopiranose",
                "AnswerImages/CarbohydrateDB/alfa-galactopiranose",
                "AnswerImages/CarbohydrateDB/beta-glicopiranose",
                "AnswerImages/CarbohydrateDB/alfa-glicopiranose"
            },
            correctIndex = 2,
            questionNumber = 36,
            isImageAnswer = true,
            isImageQuestion = true,
            questionImagePath = "QuestionImages/CarbohydrateDB/carbohydrateDB_ImageQuestionContainer36",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "carbohydrates_036",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "analisar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A beta-glicopiranose forma um anel hexagonal. Sendo 'beta', a hidroxila do carbono 1 (anomérico) está voltada para o mesmo lado (para cima) do grupo CH2OH terminal." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "Identifique abaixo a estrutura da glicose, que também pode ser nomeada como beta-D-glicopiranose",
            answers = new string[] {
                "AnswerImages/CarbohydrateDB/beta-galactopiranose",
                "AnswerImages/CarbohydrateDB/alfa-galactopiranose",
                "AnswerImages/CarbohydrateDB/alfa-glicopiranose",
                "AnswerImages/CarbohydrateDB/beta-glicopiranose"
            },
            correctIndex = 3,
            questionNumber = 37,
            isImageAnswer = true,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "carbohydrates_037",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "aplicar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Na forma beta-D-glicopiranose, a molécula é um anel de 6 membros (piranose). A letra 'beta' indica que o grupo OH do carbono 1 está virado para cima, mesma direção do CH2OH." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "AnswerImages/CarbohydrateDB/beta-galactopiranose",
                "AnswerImages/CarbohydrateDB/alfa-galactopiranose",
                "AnswerImages/CarbohydrateDB/alfa-glicopiranose",
                "AnswerImages/CarbohydrateDB/beta-glicopiranose"
            },
            correctIndex = 2,
            questionNumber = 38,
            isImageAnswer = true,
            isImageQuestion = true,
            questionImagePath = "QuestionImages/CarbohydrateDB/carbohydrateDB_ImageQuestionContainer38",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "carbohydrates_038",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "analisar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A alfa-glicopiranose tem o grupo OH do carbono anomérico (C1) voltado para baixo, na direção oposta ao plano do grupo CH2OH. Isso é o que a difere da forma beta." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "Qual a diferença entre um homopolissacarídeo e um heteropolissacarídeo?",
            answers = new string[] {
                "Um homopolissacarídeo contém apenas um tipo de monossacarídeo, um heteropolissacarídeo contém múltiplos tipos",
                "Um homopolissacarídeo é linear, um heteropolissacarídeo é ramificado",
                "Um homopolissacarídeo é solúvel em água, um heteropolissacarídeo é insolúvel",
                "Um homopolissacarídeo é um polímero, um heteropolissacarídeo é um monômero"
            },
            correctIndex = 0,
            questionNumber = 39,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "carbohydrates_039",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "compreender",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A diferença está na composição: homopolissacarídeos são formados pela repetição de um único monômero. Heteropolissacarídeos combinam dois ou mais tipos de monossacarídeos diferentes." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "Dê exemplos de homopolissacarídeos.",
            answers = new string[] {
                "Amido, glicogênio, celulose",
                "Sacarose, lactose, maltose",
                "Glicose, frutose, galactose",
                "Todos os polissacarídeos são homopolissacarídeos"},
            correctIndex = 0,
            questionNumber = 40,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "carbohydrates_040",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "lembrar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Amido, glicogênio e celulose são os melhores exemplos. Eles diferem apenas na forma de ligação e ramificação, mas todos são feitos exclusivamente da repetição de glicose." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "Dê exemplos de heteropolissacarídeos.",
            answers = new string[] {
                "Amido, glicogênio, celulose",
                "Sacarose, lactose, maltose",
                "Peptídeoglicano, glicosaminoglicanos",
                "Glicose, frutose, galactose"
            },
            correctIndex = 2,
            questionNumber = 41,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "carbohydrates_041",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "lembrar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Peptídeoglicanos (parede bacteriana) e glicosaminoglicanos (matriz extracelular animal) são estruturados por repetições de monossacarídeos diferentes (ex: alternância de açúcares ácidos e aminados)." }
        },
        new Question
        {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "Qual a principal diferença entre a estrutura da amilose e da celulose?",
            answers = new string[] {
                "A amilose é ramificada, a celulose é linear.",
                "A amilose possui ligações alfa(1 -> 4), a celulose possui ligações beta(1 -> 4).",
                "A amilose é um polímero de frutose, a celulose é um polímero de glicose.",
                "A amilose é insolúvel em água, a celulose é solúvel em água."
            },
            correctIndex = 1,
            questionNumber = 42,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "carbohydrates_042",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "compreender",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Enquanto a amilose (amido) faz ligações alfa(1->4) criando hélices para guardar energia, a celulose faz ligações beta(1->4), criando fibras retas e rígidas para estrutura." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "AnswerImages/AminoacidsDB/leucina",
                "AnswerImages/AminoacidsDB/prolina",
                "AnswerImages/AminoacidsDB/triptofano",
                "AnswerImages/AminoacidsDB/asparagina"
            },
            correctIndex = 3,
            questionNumber = 43,
            isImageAnswer = true,
            isImageQuestion = true,
            questionImagePath = "AnswerImages/SugarDB/sugar_question_43",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "carbohydrates_043",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "analisar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A asparagina é um aminoácido que pode se ligar a carboidratos. Ocorrem ligações N-glicosídicas entre o grupo amida da asparagina e o carboidrato na formação de glicoproteínas." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "AnswerImages/AminoacidsDB/leucina",
                "AnswerImages/AminoacidsDB/serina",
                "AnswerImages/AminoacidsDB/triptofano",
                "AnswerImages/AminoacidsDB/asparagina"
            },
            correctIndex = 1,
            questionNumber = 44,
            isImageAnswer = true,
            isImageQuestion = true,
            questionImagePath = "AnswerImages/SugarDB/sugar_question_44",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "carbohydrates_044",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "analisar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A serina possui uma hidroxila (-OH) em sua cadeia lateral, permitindo que ela forme ligações O-glicosídicas com carboidratos para montar estruturas como as glicoproteínas." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "Os carboidratos são moléculas formadas, principalmente, por:",
            answers = new string[] {
                "Hidrogênio, enxofre e oxigênio",
                "Carbono, hidrogênio e oxigênio",
                "Carbono, nitrogênio e fósforo",
                "Oxigênio, fósforo e magnésio",
            },
            correctIndex = 1,
            questionNumber = 45,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "carbohydrates_045",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "lembrar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "O nome hidrato de 'carbono' descreve bem a sua formação. Os três elementos fundamentais são Carbono, Hidrogênio e Oxigênio. Enxofre e fósforo não formam a base molecular deles." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "A fórmula geral mais comum dos monossacarídeos é:",
            answers = new string[] {
                "CnH2n-2On",
                "CnHnOn",
                "CnH2n+2On",
                "CnH2nOn"
            },
            correctIndex = 3,
            questionNumber = 46,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "carbohydrates_046",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "lembrar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Monossacarídeos simples obedecem rigidamente a proporção estequiométrica (CH2O)n, o que expandido matematicamente se escreve como CnH2nOn." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "A ligação que une os monossacarídeos para formar dissacarídeos e polissacarídeos chama-se:",
            answers = new string[] {
                "Ligação glicosídica",
                "Ligação peptídica",
                "Ligação dissulfeto",
                "Ligação fosfodiéster"
            },
            correctIndex = 0,
            questionNumber = 47,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "carbohydrates_047",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "lembrar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A ponte de oxigênio que une dois açúcares, liberando água, é chamada de ligação glicosídica. É a ligação fundamental na química dos carboidratos poliméricos." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "Qual polissacarídeo é a principal reserva energética dos animais?",
            answers = new string[] {
                "Amido",
                "Quitina",
                "Glicogênio",
                "Celulose"
            },
            correctIndex = 2,
            questionNumber = 48,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "carbohydrates_048",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "lembrar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "O glicogênio é o polímero de reserva energética específico para os animais. Sua estrutura altamente ramificada permite uma liberação rápida de glicose quando o animal precisa de energia." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "A quitina é um polissacarídeo estrutural encontrado em:",
            answers = new string[] {
                "Fígado humano",
                "Algas vermelhas",
                "Plantas superiores",
                "Parede celular de fungos e exoesqueleto de artrópodes"
            },
            correctIndex = 3,
            questionNumber = 49,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "carbohydrates_049",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "lembrar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A quitina compõe o exoesqueleto rígido dos insetos e artrópodes, além de fazer parte da parede celular dos fungos. Ela não é produzida nem por plantas, nem por mamíferos." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "A sacarose é formada pela união de quais monossacarídeos?",
            answers = new string[] {
                "Glicose + Frutose",
                "Glicose + Galactose",
                "Glicose + Glicose",
                "Frutose + Galactose"
            },
            correctIndex = 0,
            questionNumber = 50,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "carbohydrates_050",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "lembrar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A sacarose comercial é extraída da cana e da beterraba. Ela é um dissacarídeo composto exatamente pela condensação de uma molécula de glicose e uma de frutose." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "A glicose, a frutose e a galactose são exemplos de:",
            answers = new string[] {
                "Oligossacarídeos",
                "Monossacarídeos",
                "Dissacarídeos",
                "Polissacarídeos"
            },
            correctIndex = 1,
            questionNumber = 51,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "carbohydrates_051",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "lembrar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Eles são a forma mais simples (açúcares não hidrolisáveis). Mono = um. Não precisam ser quebrados para serem absorvidos e atuam como blocos construtores." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "A celulose difere do amido principalmente porque:",
            answers = new string[] {
                "É solúvel em água, enquanto o amido não é",
                "Possui ligações β(1→4), enquanto o amido possui α(1→4)",
                "É formada por frutose, enquanto o amido é formado por glicose",
                "É composta por galactose, e não glicosedeos"
            },
            correctIndex = 1,
            questionNumber = 52,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "carbohydrates_052",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "compreender",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A ligação beta(1->4) da celulose a torna resistente às enzimas digestivas humanas (amilases) e permite a formação de fortes microfibrilas, o que a difere das ligações alfa do amido." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "Qual das funções abaixo NÃO está relacionada aos carboidratos?",
            answers = new string[] {
                "Estrutura celular",
                "Fornecimento de energia",
                "Armazenamento de energia",
                "Catálise enzimática direta"
            },
            correctIndex = 3,
            questionNumber = 53,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "carbohydrates_053",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "compreender",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Os carboidratos dão estrutura (celulose, quitina) e energia (amido, glicogênio). No entanto, quem atua como catalisadores diretos (enzimas) são, em regra quase exclusiva, as proteínas." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "Os carboidratos também são conhecidos como:",
            answers = new string[] {
                "Lípidos",
                "Glicídios",
                "Aminoácidos",
                "Nucleotídeos"
            },
            correctIndex = 1,
            questionNumber = 54,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "carbohydrates_054",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "lembrar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "O termo glicídios é sinônimo de carboidratos, referindo-se ao sabor doce ('glico') que muitas dessas moléculas menores possuem." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "A fórmula geral mais comum dos monossacarídeos é:",
            answers = new string[] {
                "Cn(H₂O)n",
                "CnH₂nOn",
                "Cn(H₂O)2n",
                "CnHnOn"
            },
            correctIndex = 1,
            questionNumber = 55,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "carbohydrates_055",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "lembrar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A fórmula mais aceita de um monossacarídeo simples segue a proporção 1:2:1 (Carbono, Hidrogênio, Oxigênio). Ou seja: CnH2nOn." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "Qual dos seguintes é um monossacarídeo?",
            answers = new string[] {
                "Sacarose",
                "Maltose",
                "Glicose",
                "Amido"
            },
            correctIndex = 2,
            questionNumber = 56,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "carbohydrates_056",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "lembrar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Amido, sacarose e maltose são formados por múltiplas unidades. Apenas a glicose é uma unidade basal, ou seja, um monossacarídeo que não pode ser mais hidrolisado." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "A sacarose, encontrada no açúcar de mesa, é formada por:",
            answers = new string[] {
                "Glicose + Frutose",
                "Glicose + Galactose",
                "Frutose + Galactose",
                "Glicose + Glicose"
            },
            correctIndex = 0,
            questionNumber = 57,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "carbohydrates_057",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "lembrar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Quando o açúcar de mesa (sacarose) entra no nosso trato digestivo, a enzima invertase (ou sucrase) o quebra em duas metades energéticas: uma glicose e uma frutose." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "O amido é o principal polissacarídeo de reserva:",
            answers = new string[] {
                "Animal",
                "Fúngico",
                "Vegetal",
                "Bacteriano"
            },
            correctIndex = 2,
            questionNumber = 58,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "carbohydrates_058",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "lembrar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Vegetais produzem sua energia pela fotossíntese e precisam armazenar o excedente em raízes e sementes. Eles fazem isso principalmente empacotando glicose na forma de amido." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "O glicogênio é o polissacarídeo de reserva característico de:",
            answers = new string[] {
                "Plantas",
                "Fungos e animais",
                "Bactérias",
                "Protozoários"
            },
            correctIndex = 1,
            questionNumber = 59,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "carbohydrates_059",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "lembrar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Diferente das plantas, fungos e animais resolvem a questão do estoque de energia polimerizando a glicose em uma estrutura super-ramificada chamada glicogênio." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "A celulose tem como função principal nos vegetais:",
            answers = new string[] {
                "Armazenar energia",
                "Dar resistência à parede celular",
                "Servir como reserva osmótica",
                "Participar da respiração celular"
            },
            correctIndex = 1,
            questionNumber = 60,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "carbohydrates_060",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "lembrar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Plantas não têm esqueletos ósseos. Elas mantêm a forma física graças à celulose, cujas fibras resistentes envelopam as células e compõem a parede celular rígida." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "A lactose, presente no leite, é formada por:",
            answers = new string[] {
                "Glicose + Glicose",
                "Glicose + Galactose",
                "Glicose + Frutose",
                "Galactose + Frutose"
            },
            correctIndex = 1,
            questionNumber = 61,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "carbohydrates_061",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "lembrar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Para os bebês poderem digerir o leite, a enzima lactase atua no intestino quebrando a lactose. Esse açúcar é a união química de uma glicose com uma galactose." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "Entre as alternativas abaixo, qual é um polissacarídeo estrutural?",
            answers = new string[] {
                "Amido",
                "Glicogênio",
                "Celulose",
                "Maltose"
            },
            correctIndex = 2,
            questionNumber = 62,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "carbohydrates_062",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "lembrar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Amido e glicogênio são para estocar energia. A celulose, pelo contrário, não é mobilizável, ela cria paredes celulares duras e atua primariamente como estrutura vegetal." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "A fórmula geral mais comum dos carboidratos é:",
            answers = new string[] {
                "Cn(H₂O)n",
                "CnH₂nOn",
                "CnH₂n+₂On",
                "CnHnOn"
            },
            correctIndex = 0,
            questionNumber = 63,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "carbohydrates_063",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "lembrar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Em monossacarídeos puros, para cada átomo de carbono existe uma molécula de água correspondente, resultando na proporção fundamental Cn(H2O)n." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "A glicose é classificada como:",
            answers = new string[] {
                "Dissacarídeo",
                "Monossacarídeo",
                "Polissacarídeo",
                "Oligossacarídeo"
            },
            correctIndex = 1,
            questionNumber = 64,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "carbohydrates_064",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "lembrar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Glicose é a moeda energética base das células. Ela é a unidade fundamental não divisível dos carboidratos, recebendo a classificação biológica de monossacarídeo." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "A sacarose é formada pela união de:",
            answers = new string[] {
                "Glicose + Glicose",
                "Glicose + Galactose",
                "Glicose + Frutose",
                "Glicose + Manose"
            },
            correctIndex = 2,
            questionNumber = 65,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "carbohydrates_065",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "lembrar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A sacarose (açúcar comum) só se forma no citosol das células vegetais, unindo os monômeros produzidos na fotossíntese: a glicose combinada à frutose." }
        },
         new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "Qual destes carboidratos é considerado um polissacarídeo de armazenamento em animais?",
            answers = new string[] {
                "Amido",
                "Celulose",
                "Glicogênio",
                "Quitina"
            },
            correctIndex = 2,
            questionNumber = 66,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "carbohydrates_066",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "lembrar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Enquanto plantas usam amido, nós e outros animais usamos o glicogênio. Ele é abundante nos músculos para uso local e no fígado para regular a glicose do sangue." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "Qual destes carboidratos é um polissacarídeo estrutural presente na parede celular de vegetais?",
            answers = new string[] {
                "Amido",
                "Celulose",
                "Maltose",
                "Lactose"
            },
            correctIndex = 1,
            questionNumber = 67,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "carbohydrates_067",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "lembrar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A celulose é o composto orgânico mais abundante na biosfera. Como polissacarídeo estrutural, ela forma feixes super-resistentes que definem a parede das células vegetais." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "Qual destes carboidratos está presente no leite?",
            answers = new string[] {
                "Sacarose",
                "Lactose",
                "Maltose",
                "Glicogênio"
            },
            correctIndex = 1,
            questionNumber = 68,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "carbohydrates_068",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "lembrar",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "O açúcar do leite não é a sacarose. Os mamíferos sintetizam nas glândulas mamárias o dissacarídeo conhecido como lactose." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "Os carboidratos podem ser classificados de acordo com:",
            answers = new string[] {
                "O número de radicais R",
                "O número de átomos de carbono e grupos funcionais",
                "A presença de ácidos graxos",
                "O número de ligações peptídicas"
            },
            correctIndex = 1,
            questionNumber = 69,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "carbohydrates_069",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "compreender",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A classificação química primária se baseia em duas coisas: quantos átomos de carbono existem (ex: hexose = 6C) e o tipo de grupo carbonila (aldeído nas aldoses, cetona nas cetoses)." }
        },
        new Question {
            questionDatabankName = "CarbohydratesQuestionDatabase",
            questionText = "Qual das opções representa uma função principal dos carboidratos nos organismos vivos?",
            answers = new string[] {
                "Atuar como catalisadores biológicos",
                "Armazenar informações genéticas",
                "Fornecer energia e servir como reserva energética",
                "Compor membranas celulares"
            },
            correctIndex = 2,
            questionNumber = 70,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "carbohydrates_070",
            topic = "carbohydrates",
            subtopic = null,
            displayName = "Carboidratos",
            bloomLevel = "compreender",
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Embora façam parte de membranas e RNA/DNA, a característica marcante e função quantitativamente principal dos carboidratos no mundo vivo é fornecer e armazenar energia." }
        }
    };

    public List<Question> GetQuestions() => questions;
    public QuestionSet GetQuestionSetType() => QuestionSet.carbohydrates;
    public string GetDatabankName()  => "CarbohydratesQuestionDatabase";
    public string GetDisplayName()   => "Carboidratos";
    public bool IsDatabaseInDevelopment() => databaseInDevelopment;

}